### ISSUE TITLE
Error PHP7.2

### ISSUE THREAD

**Issue by vsatmydynipnet** [david63/userdefaults#1]
Love this extension and the main switch to auto subscribe to topics works out. setting other stuff to mail not. there is this error:

[Thu Aug 15 16:13:02.372082 2019] [fcgid:warn] [pid 10695] [client 216.233.116.18:51514] mod_fcgid: stderr: PHP Fatal error:  Uncaught Error: Class 'david63\\userdefaults\\controller\\constants' not found in /var/www/vhosts/forum.myforum.com/httpdocs/ext/david63/userdefaults/controller/admin_controller.php:248, referer: https://forum.myforum.com/adm/index.php?sid=dcaa9cd8575fd38b0c7fe87bf2c16822&i=-david63-userdefaults-acp-userdefaults_module&mode=manage
[Thu Aug 15 16:13:02.372162 2019] [fcgid:warn] [pid 10695] [client 216.233.116.18:51514] mod_fcgid: stderr: Stack trace:, referer: https://forum.myforum.com/adm/index.php?sid=dcaa9cd8575fd38b0c7fe87bf2c16822&i=-david63-userdefaults-acp-userdefaults_module&mode=manage
[Thu Aug 15 16:13:02.372173 2019] [fcgid:warn] [pid 10695] [client 216.233.116.18:51514] mod_fcgid: stderr: #0 /var/www/vhosts/forum.myforum.com/httpdocs/ext/david63/userdefaults/controller/admin_controller.php(112): david63\\userdefaults\\controller\\admin_controller->set_options(), referer: https://forum.myforum.com/adm/index.php?sid=dcaa9cd8575fd38b0c7fe87bf2c16822&i=-david63-userdefaults-acp-userdefaults_module&mode=manage
[Thu Aug 15 16:13:02.372183 2019] [fcgid:warn] [pid 10695] [client 216.233.116.18:51514] mod_fcgid: stderr: #1 /var/www/vhosts/forum.myforum.com/httpdocs/ext/david63/userdefaults/acp/userdefaults_module.php(26): david63\\userdefaults\\controller\\admin_controller->display_options(), referer: https://forum.myforum.com/adm/index.php?sid=dcaa9cd8575fd38b0c7fe87bf2c16822&i=-david63-userdefaults-acp-userdefaults_module&mode=manage
[Thu Aug 15 16:13:02.372193 2019] [fcgid:warn] [pid 10695] [client 216.233.116.18:51514] mod_fcgid: stderr: #2 /var/www/vhosts/forum.myforum.com/httpdocs/includes/functions_module.php(676): david63\\userdefaults\\acp\\userdefaults_module->main('\\\\david63\\\\userde...', 'manage'), referer: https://forum.myforum.com/adm/index.php?sid=dcaa9cd8575fd38b0c7fe87bf2c16822&i=-david63-userdefaults-acp-userdefaults_module&mode=manage
[Thu Aug 15 16:13:02.372203 2019] [fcgid:warn] [pid 10695] [client 216.233.116.18:51514] mod_fcgid: stderr: #3 /var/www/vhosts/forum.myforum.com/httpdocs/adm/index.php(82): p_master->load_active(), referer: https://forum.myforum.com/adm/index.php?sid=dcaa9cd8575fd38b0c7fe87bf2c16822&i=-david63-userdefaults-acp-userdefaults_module&mode=manage
[Thu Aug 15 16:13:02.372214 2019] [fcgid:warn] [pid 10695] [client 216.233.116.18:51514] mod_fcgid: stderr: #4 {main}, referer: https://forum.myforum.com/adm/index.php?sid=dcaa9cd8575fd38b0c7fe87bf2c16822&i=-david63-userdefaults-acp-userdefaults_module&mode=manage
[Thu Aug 15 16:13:02.372224 2019] [fcgid:warn] [pid 10695] [client 216.233.116.18:51514] mod_fcgid: stderr:   thrown in /var/www/vhosts/forum.myforum.com/httpdocs/ext/david63/userdefaults/controller/admin_controller.php on line 248, referer: https://forum.myforum.com/adm/index.php?sid=dcaa9cd8575fd38b0c7fe87bf2c16822&i=-david63-userdefaults-acp-userdefaults_module&mode=manage

**Comment by DavidZemon** [comment]
I think I may be running into the same problem. My server is running php 7.2.22 and when I try to save changes, the server throws a 500 error back at me. Unfortunately, i don't have access to syslog and I'm guessing that's where the error is being dumped.

**Comment by Sylver35** [comment]
Fixed in the 3.1.0-RC1 version
